import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { AdminProvider } from "@/context/admin";

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Threadles Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" />
      </head>
      <body className={inter.className}>
        <AdminProvider>
          <Header />
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          {children}
          <Footer />
        </AdminProvider>
      </body>
    </html>
  );
}
